name: Ability Draft
description: A problem in the Ability Draft game mode

labels: ["ability-draft"]

body:
  - type: markdown
    attributes:
      value: |
        ### ❕Before making the post.
        * First, you should use Search to find out if the issue you want to post has been already posted in this bug tracker. 
          If this is the case - **please, do not post duplicates**. 
          Just **upvote with "👍" reaction** the original issue and comment extra details if any. 
        * And only then, if your issue was not posted before - you can start typing your post using below. 
          Try to provide as much information as possible about the bug.
        * Thank you!

  - type: textarea
    id: desc
    attributes:
      label: Description
      placeholder: What is the problem?
    validations:
      required: true

  - type: input
    id: match-id
    attributes:
      label: Example Match ID (and possibly Timestamp)
      placeholder: ex. 6575941888 - 03:22
    validations:
      required: true