name: Ability Bug zzzz
description: An ability behaves in a way it probably shouldn't!

labels: ["ability"]

body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: _Please search to see if an issue already exists for the bug you encountered. **I DON\'T MAKE THIS TICK BOX FOR COSMETIC.**_
    options:
    - label: I have searched the existing issues
      required: true
      
- type: checkboxes
  attributes:
    label: Have you read the FAQ?
    description: _Make sure you actually visit the [**FAQ**](https://github.com/qnblackcat/uYouPlus/wiki/FAQ) page! **I DON\'T MAKE THIS TICK BOX FOR COSMETIC**_
    options:
    - label: Yes, I did read the FAQ
      required: true
      
  - type: input
    id: name
    attributes:
      label: Ability name
      placeholder: ex. Spell steal
    validations:
      required: true
    
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: _Please attach videos or screenshots if possible_
      placeholder: What is the problem? Describe steps to reproduce the issue.
    validations:
      required: true

  - type: input
    id: match-id
    attributes:
      label: Example Match ID (and possibly Timestamp)
      placeholder: ex. 6575941888 - 03:22
    validations:
      required: true
