name: Bug
description: Report broken or incorrect behaviour.

body:
  - type: checkboxes
    attributes:
      label: Did you search for your bug in existing issues?
      description: |
        Please search to see if an issue already exists for the bug you encountered.
        If this is the case - **please, do not post duplicates**.
        Instead, just **upvote with "👍" reaction** the original issue and comment extra details if any. 
      options:
      - label: Yes, I have searched the existing issues and my post is not a duplicate. 
        required: true

  - type: checkboxes
    attributes:
      label: Have you read the FAQ?
      description: Make sure you read the FAQ in the [**README**](https://github.com/ValveSoftware/Dota2-Gameplay#readme) page.
      options:
      - label: Yes, I read the FAQ.
        required: true
  
  - type: dropdown
    attributes:
      multiple: false
      label: Choose bug category
      options:
        - Ability bug
        - Item bug
        - Cosmetic bug
        - Incorrect tooltip
        - Ability Draft
        - Other
      validations:
        required: true

  - type: input
    id: name
    attributes:
      label: Summary
      description: A simple summary of your bug report. You can just list names of bugged items/abilities here. 
      placeholder: ex. Spell steal, Blink Dagger, 
    validations:
      required: true
    
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: |
        What is the problem? Describe steps to reproduce the issue. Please attach videos or screenshots if possible.
      placeholder: What is the problem?
    validations:
      required: true

  - type: input
    id: match-id
    attributes:
      label: Example Match ID (and possibly Timestamp)
      placeholder: ex. 6575941888 - 03:22
    validations:
      required: true
