on:
  push:
    branches:
      - 'main'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout BRANCH
        uses: actions/checkout@v3
        with:
          ref: testpage
      - name: REBASE
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git rebase main
          git push testpage
