on:
  push:
    branches:
      - 'main'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout BRANCH
        uses: actions/checkout@v3
        with:
          ref: testpage
      - name: FETCH MAIN 
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: CREATE PULL REQUEST
        uses: peter-evans/create-pull-request@v5
        with:
          branch: testpage-promotion
