on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: testpage
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git rebase main
          git push origin testpage
